# Pfade
Pfad Datei: 'C:\Users\ma1011572\OneDrive\MSc_EnergyAndEnvironment\P9\18_Paperdraft\Berechnung_Windisch\csv\Batterieberechnungen\LiAkku_Anlage2.csv'
Pfad Resultate: 'C:\Users\ma1011572\OneDrive\MSc_EnergyAndEnvironment\P9\18_Paperdraft\Bilder'

# Dateiname Plot Verluste:
Dateiname: 'Verluste_Windisch_15W_90Autarkie_Li'

# Dateiname Plot genutzte energie, Verluste und Überschuss:
Dateiname Gesamtenergie: 'Energienutzung_Windisch_15W_90Autarkie_Li'

# MPPT-Eigenschaften wie sie in den Berechnungen eingestellt waren
MPPT_Wirkungsgrad: 98
MPPT_Eigenverbrauch: 0.24
MPPT_Trackingverlust: 0.5