# Pfad zur Datei, die ausgewertet werden soll:
Pfad_Datei_Resultate: 'C:\Users\ma1011572\OneDrive\MSc_EnergyAndEnvironment\P9\18_Paperdraft\Berechnung_Windisch\csv\Resultate_alle_Anlagen.csv'

# Pfad zur Ablage des Plots:
Pfad_Plot: 'C:\Users\ma1011572\OneDrive\MSc_EnergyAndEnvironment\P9\18_Paperdraft\Bilder'

# Pfad zur Ablage des Poster-Plots (quadratisches Format):
Pfad_Plot_Poster: 'C:\Users\ma1011572\OneDrive\MSc_EnergyAndEnvironment\P9\19_Poster\Grafiken'
